# Generated by Django 4.2.1 on 2023-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_courses', models.CharField(max_length=100, null=True)),
                ('finished_courses', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255, null=True)),
                ('l_name', models.CharField(max_length=255, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
