# Generated by Django 4.2.1 on 2023-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
