
version: '3'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: whatever
    volumes:
    - my_own_data:/var/lib/mysql  

  node:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
 my_own_data:     
